### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MohamedAtia-B** [mbdavid/FileDB#1]
I have some questions, ordered by priority, and your support is highly appreciated.

Is it possible to add a new optional (nullable) attribute to the file? The attribute is a Guid named "CorrelationID", it means that a group of files are correlated with one ID so that later on we can retrieve all the files in the same correlation. If yes how to achieve this without breaking anything.

Did you try the FleDB on production? are there any tips? 

Did the .dat file get corrupted before? if yes is there a contingency?
Can the .dat file get infected (by a virus)?

**Comment by mbdavid** [comment]
Hi @MohamedAtia-B,

FileDB is a quite old project that I use in production many times, in big projects. I had, in a single project, more than 400gb data using FileDB (splitted in 3GB each file). I never had corrupted file, but I always have a daily backup.

The is no possible to get virus inside this datafile because they are not executable/loaded direct by any application. But off course, they can store virus file if you try store an file with virus.

About updates, I had no plan to change this anymore because now I use LiteDB datafile with FileStorage feature that are same as FileDB but with support to flexible metadata for each file.

**Comment by MohamedAtia-B** [comment]
Thank you for your prompt response, I will switch to LiteDB as u recommended.
